server {
    listen 80;
    server_name api.licensify.kr;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name api.licensify.kr;

    ssl_certificate     /etc/letsencrypt/live/api.licensify.kr/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/api.licensify.kr/privkey.pem;

    location / {
        resolver 127.0.0.11 valid=10s;
        set $upstream app-green:8080;
        proxy_pass http://$upstream;

        # 클라이언트의 실제 정보를 백엔드(app)에 전달
        # 없으면 Spring 입장에서 모든 요청이 nginx(127.0.0.1)에서 온 것처럼 보임
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
